### ISSUE TITLE
Automatic detection of auth server using container

### ISSUE THREAD

**Issue by otsakir** [Mobicents/restcomm-identity#16]
Use container to automatically detect the IP/host address restcomm-identity is running on. It is assumed that this is the same with the address the auth server is running on.

**Comment by otsakir** [comment]
Ran some tests. Detection works but Keycloak adapter configuration file (keycloak.json) needs to be updated too for this to operate smoothly.

**Comment by otsakir** [comment]
Just noticed that keycloak.json/auth-server-url can also be relative. That's the way to go since restcomm-identity app also sits together with the auth server. Looks like no parameterization will be required for keycloak.json.

**Comment by otsakir** [comment]
Automatic detections fails when enumerating connectors. For some reason the same method that works on Jboss/Restcomm fails in keycloak/wildfly. 
Here is the exception:

16:14:10,432 ERROR [org.jboss.as.controller.management-operation](ServerService Thread Pool -- 67) WFLYCTL0013: Operation ("read-attribute") failed - address: ([
    ("socket-binding-group" => "standard-sockets"),
    ("socket-binding" => "http")
]) - failure description: "WFLYCTL0216: Management resource '[(\"socket-binding-group\" => \"standard-sockets\")]' not found"
16:14:10,435 ERROR [com.restcomm.identity.http.utils.UriUtils](ServerService Thread Pool -- 67) Exception during HTTP Connectors discovery: : javax.management.AttributeNotFoundException: "WFLYCTL0216: Management resource '[(\"socket-binding-group\" => \"standard-sockets\")]' not found"
    at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:254)
    at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:212)
    at org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.getAttribute(ModelControllerMBeanServerPlugin.java:129)
    at org.jboss.as.jmx.PluggableMBeanServerImpl.getAttribute(PluggableMBeanServerImpl.java:400)
    at com.restcomm.identity.http.utils.UriUtils.getHttpConnectors(UriUtils.java:71)
    at com.restcomm.identity.http.utils.UriUtils.resolve(UriUtils.java:107)
    at com.restcomm.identity.configuration.Configuration.getAuthServerUrlBase(Configuration.java:80)
    at com.restcomm.identity.configuration.Configuration.<init>(Configuration.java:47)
    at com.restcomm.identity.configuration.Configuration.createOnce(Configuration.java:61)
    at com.restcomm.identity.bootstrap.RestcommIdentityInitializationServlet.init(RestcommIdentityInitializationServlet.java:18)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
    at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
    at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:230)
    at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:131)
    at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:511)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jboss.threads.JBossThread.run(JBossThread.java:320)

16:14:10,438 ERROR [org.jboss.msc.service.fail](ServerService Thread Pool -- 67) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./restcomm-identity: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./restcomm-identity: java.lang.NullPointerException
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.NullPointerException
    at com.restcomm.identity.http.utils.UriUtils.resolve(UriUtils.java:141)
    at com.restcomm.identity.configuration.Configuration.getAuthServerUrlBase(Configuration.java:80)
    at com.restcomm.identity.configuration.Configuration.<init>(Configuration.java:47)
    at com.restcomm.identity.configuration.Configuration.createOnce(Configuration.java:61)
    at com.restcomm.identity.bootstrap.RestcommIdentityInitializationServlet.init(RestcommIdentityInitializationServlet.java:18)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
    at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
    at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:230)
    at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:131)
    at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:511)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
    ... 6 more
